// Generated by uniffi-bindgen-react-native
#include "react-native-russh.h"
#include "generated/react_native_russh.hpp"

namespace russh {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeReactNativeRussh::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}