// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-whip-ssh.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "WhipSshSpec.h"

@interface WhipSsh : NSObject <NativeWhipSshSpec>
#else
#import <React/RCTBridgeModule.h>

@interface WhipSsh : NSObject <RCTBridgeModule>
#endif

@end