// Generated by uniffi-bindgen-react-native
#include "react-native-whip-ssh.h"
#include "generated/whip_ssh.hpp"

namespace whipssh {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeWhipSsh::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}