plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    google()
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation 'com.android.tools.build:gradle:8.12.0'
}

gradlePlugin {
    plugins {
        reactNativeFabricCrashMitigation {
            id = 'whip.react-native-fabric-crash-mitigation'
            implementationClass = 'ReactNativeFabricCrashMitigationPlugin'
        }
    }
}
