// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-russh.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "ReactNativeRusshSpec.h"

@interface Russh : NSObject <NativeRusshSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Russh : NSObject <RCTBridgeModule>
#endif

@end