/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=feedback-worker/wrangler.jsonc --include-runtime=false feedback-worker/worker-configuration.d.ts` (hash: 05bf937d69ce58c1273b0f2e8c3df4db)
interface __BaseEnv_Env {
	DB: D1Database;
	REVENUECAT_WEBHOOK_AUTHORIZATION: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "REVENUECAT_WEBHOOK_AUTHORIZATION">> {}
}
