import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const readSource = (path: string) => readFileSync(resolve(__dirname, `../${path}`), 'utf8');

test('gates app glass across bars and rows behind its experiment and background image', () => {
  const app = readSource('App.tsx');
  const glass = readSource('src/components/GlassSurface.tsx');
  const appDelegate = readSource('ios/HerdR/AppDelegate.swift');
  const settings = readSource('src/components/SettingsScreen.tsx');
  const connection = readSource('src/components/ConnectionScreen.tsx');
  const hosts = readSource('src/components/HostsScreen.tsx');
  const herd = readSource('src/components/HerdScreen.tsx');
  const hostRail = readSource('src/components/LiveSessionRail.tsx');
  const workspaceRail = readSource('src/components/WorkspaceRail.tsx');
  const appUi = readSource('src/components/app-ui.tsx');
  const globalKeychain = readSource('src/components/GlobalKeychainScreen.tsx');
  const knownHosts = readSource('src/components/KnownHostsScreen.tsx');

  expect(app).toContain('enabled={appGlassEnabled && Boolean(appBackgroundImageUri)}');
  expect(glass).toContain('glass?.enabled === true');
  expect(glass).toContain('useContext(GlassContext)?.enabled === true');
  expect(glass).toContain("from '@callstack/liquid-glass'");
  expect(glass).toContain('const renderLiquidGlass = enabled && isLiquidGlassSupported;');
  expect(glass).toContain('if (!enabled && !renderLiquidGlass)');
  expect(glass).toContain('renderLiquidGlass ? (');
  expect(glass).toContain('<LiquidGlassView');
  expect(glass).toContain('effect="clear"');
  expect(glass).toContain("colorScheme={isDark ? 'dark' : 'light'}");
  expect(glass).toContain('shapeClassName={className}');
  expect(glass).toContain('liquidGlassShapeStyle(shapeClassName)');
  expect(glass).toContain("className.includes('rounded-full')");
  expect(glass).toContain('pointerEvents="none"');
  expect(glass).not.toContain('interactive');
  expect(glass).toContain("console.info('[LiquidGlass] capability'");
  expect(glass).toContain('isLiquidGlassSupported,');
  expect(glass).toContain('legacyGlassEnabled: enabled,');
  expect(glass).toContain('[LiquidGlass] runtime');
  expect(appDelegate).toContain('[LiquidGlass] native capability supported=%@');
  expect(appDelegate).toContain('NSClassFromString("UIGlassEffect")');
  expect(glass).toContain('backgroundColor: colors.surface');
  expect(glass).toContain('blurMethod="dimezisBlurViewSdk31Plus"');
  expect(glass).toContain("Platform.OS !== 'android'");
  expect(glass).toContain('blurTarget={glass?.blurTarget}');
  expect(glass).toContain("'rgba(20,22,34,0.38)'");
  expect(glass).toContain("'rgba(255,255,255,0.42)'");
  expect(settings.match(/<GlassSurface/g)?.length).toBeGreaterThanOrEqual(8);
  expect(connection).toContain('<GlassSurface className="rounded-lg border border-white/30 p-4 dark:border-white/10">');
  expect(connection).toContain('const appGlassEnabled = useAppGlassEnabled();');
  expect(connection).toContain("variant={appGlassEnabled ? 'ghost' : 'secondary'}");
  expect(connection).toContain("variant={appGlassEnabled ? 'ghost' : 'default'}");
  expect(connection.match(/appGlassControlStyle\(false, colors\)/g)?.length).toBeGreaterThanOrEqual(4);
  expect(connection.match(/appGlassControlStyle\(true, colors\)/g)?.length).toBeGreaterThanOrEqual(2);
  expect(connection).toContain('className="flex-1">');
  expect(connection).not.toContain('className="flex-1 bg-background">');
  expect(app.match(/<AppBackground uri=\{appBackgroundImageUri\} dimming=\{appBackgroundDimming\} \/>/g)).toHaveLength(4);
  expect(hosts).toContain('<GlassSurface className="min-h-[88px]');
  expect(hosts).toContain('<AgentStatusMedallion');
  expect(readSource('src/components/app-ui.tsx')).toContain('<GlassSurface\n        className="items-center justify-center rounded-full border"');
  expect(herd).toContain('<GlassBackdrop shapeClassName="rounded-xl" />');
  expect(hostRail).toContain('appGlassEnabled ? appGlassControlStyle(active, colors) : undefined');
  expect(workspaceRail).toContain('appGlassEnabled ? appGlassControlStyle(active, colors) : undefined');
  expect(herd.match(/style=\{appGlassEnabled \? appGlassControlStyle\(false, colors\) : undefined\}/g)).toHaveLength(2);
  expect(herd).not.toContain("variant={appGlassEnabled ? 'ghost' : 'default'}");
  expect(herd.match(/variant=\{appGlassEnabled \? 'ghost' : 'secondary'\}/g)).toHaveLength(2);
  expect(hosts).toContain('<StatusBadge status={state} label={label} />');
  expect(herd).toContain('<StatusBadge');
  expect(appUi).toContain('const appGlassEnabled = useAppGlassEnabled();');
  expect(appUi).toContain('? appGlassControlStyle(false, colors)');
  expect(appUi).toContain(': { borderColor: colors.divider }');
  expect(globalKeychain).toContain('const appGlassEnabled = useAppGlassEnabled();');
  expect(globalKeychain.match(/<GlassSurface/g)?.length).toBeGreaterThanOrEqual(3);
  expect(globalKeychain).toContain("variant={appGlassEnabled ? 'ghost' : 'secondary'}");
  expect(globalKeychain).toContain("variant={appGlassEnabled ? 'ghost' : 'default'}");
  expect(globalKeychain).not.toContain('className="flex-1 bg-background"');
  expect(knownHosts.match(/<GlassSurface/g)?.length).toBeGreaterThanOrEqual(2);
  expect(knownHosts).not.toContain('className="flex-1 bg-background"');
});
